services:
  # api:
  #   container_name: driveappapi
  #   build:
  #     context: .
  #     dockerfile: ./k8/images/api/Dockerfile
  #   env_file:
  #     - ./apps/api/.env
  #   ports:
  #     - 8080:8080
  # adminpanel:
  #   container_name: driveappadminpanel
  #   build:
  #     context: .
  #     dockerfile: ./k8/images/adminpanel/Dockerfile
  #   env_file:
  #     - ./apps/adminpanelv2/.env
  #   ports:
  #     - 3000:3000

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  pgdata:
