services:
  api:
    container_name: driveappapi
    build:
      context: .
      dockerfile: ./k8/images/api/Dockerfile
    env_file:
      - ./apps/api/.env
    ports:
      - 8080:8080
  adminpanel:
    container_name: driveappadminpanel
    build:
      context: .
      dockerfile: ./k8/images/adminpanel/Dockerfile
    env_file:
      - ./apps/adminpanelv2/.env
    ports:
      - 3000:3000
  db:
    container_name: driveappdb
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: driveappdb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
